### ISSUE TITLE
Tags Are (Often) Atoms

### ISSUE THREAD

**Issue by mischov** [Overbryd/myhtmlex#2]
The existing Elixir HTML parsers that parse into a format similar to `myhtmlex` (I call the format a tuple-tree) parse tag names as strings, while you appear to parse known HTML tag names as atoms. This breaks compatibility with any existing users of the tuple-tree format (and generally leads to ambiguity as to whether a name is a string or an atom, requiring additional checks when handling nodes).

Are there reasons why you've chosen to parse known HTML tag names as atoms? Would you consider just using strings instead (or allowing that behavior to be configured), to maintain compatibility?

**Comment by Overbryd** [comment]
Ah sure, that idea came from my "exoml" implementation, where I
specifically choose "nil" as children for self-closing tags, and just
binaries as text nodes.

I thought, since myhtml is a spec-conform parser, to leverage that bit of
information into the result.

Using atoms for known (i.e. html spec conform) html tags enriches the
resulting tree.

Not to break the existing protocol, I will make that behaviour configurable.

**Comment by Overbryd** [comment]
Now parsing into mochiweb-tree style by default with `master@8226077`.

Please check if you find further inconsistencies with the 3-tuple, all binary, empty lists tree style.
